title: Seattle Performing Arts Lovers
author: Derek Cutting
# email: 
description: > # this means to ignore newlines until "baseurl:"
  A community of Seattleites who love live performance in all its forms.
baseurl: ""
url: https://spal.club
lang: en # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: native # this specifies color scheme for syntax highlighting
# github_username: kamikat
# twitter_username: kamikat_bot
# instagram_username: kamikat_bot

# Build settings
markdown: kramdown
theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock
